---
apiVersion: v1
kind: Secret
metadata:
  name: test-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  insecure: "false"
  url: git@github.com:andrekloster/confluent-test.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    INSERT_KEY_HERE
    -----END OPENSSH PRIVATE KEY-----
