---
confluent:
  namespace: confluent
  connect:
    name: connect
    replicas: 1
    image:
      application: confluentinc/cp-server-connect:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    dependencies:
      kafka:
        bootstrapEndpoint: kafka:9071
  controlcenter:
    name: controlcenter
    namespace: confluent
    replicas: 1
    image:
      application: confluentinc/cp-enterprise-control-center:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    dataVolumeCapacity: 10Gi
    externalAccess:
      nodePort:
        host: kube-test-1.domus-server.local
        nodePortOffset: 30100
    dependencies:
      schemaRegistry:
        url: http://schemaregistry.confluent.svc.cluster.local:8081
      ksqldb:
        - name: ksqldb
          url: http://ksqldb.confluent.svc.cluster.local:8088
      connect:
        - name: connect
          url: http://connect.confluent.svc.cluster.local:8083
  kafka:
    name: kafka
    replicas: 3
    image:
      application: confluentinc/cp-server:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    dataVolumeCapacity: 10Gi
    listeners:
      external:
        externalAccess:
          nodePort:
            host: kube-test-1.domus-server.local
            nodePortOffset: 30000
    dependencies:
      kRaftController:
        clusterRef:
          name: kraftcontroller
  kafkaRestProxy:
    name: kafkarestproxy
    replicas: 1
    image:
      application: confluentinc/cp-kafka-rest:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    dependencies:
      schemaRegistry:
        url: http://schemaregistry.confluent.svc.cluster.local:8081
  kraftController:
    name: kraftcontroller
    dataVolumeCapacity: 10Gi
    image:
      application: docker.io/confluentinc/cp-server:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    replicas: 3
  ksqlDB:
    name: ksqldb
    replicas: 1
    image:
      application: confluentinc/cp-ksqldb-server:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    dataVolumeCapacity: 10Gi
  schemaRegistry:
    name: schemaregistry
    replicas: 3
    image:
      application: confluentinc/cp-schema-registry:7.7.0
      init: confluentinc/confluent-init-container:2.9.0
    externalAccess:
      nodePort:
        host: kube-test-1.domus-server.local
        nodePortOffset: 30200
