---
confluent:
  imageRegistry: container-registry.domus-server.de/public
  namespace: confluent
  connect:
    name: connect
    replicas: 1
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-server-connect:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
    dependencies:
      kafka:
        bootstrapEndpoint: kafka:9071
  controlcenter:
    name: controlcenter
    namespace: confluent
    replicas: 1
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-enterprise-control-center:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
    dataVolumeCapacity: 10Gi
    dependencies:
      schemaRegistry:
        url: http://schemaregistry.confluent.svc.cluster.local:8081
      ksqldb:
        - name: ksqldb
          url: http://ksqldb.confluent.svc.cluster.local:8088
      connect:
        - name: connect
          url: http://connect.confluent.svc.cluster.local:8083
  kafka:
    name: kafka
    replicas: 3
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-server:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
    dataVolumeCapacity: 10Gi
    dependencies:
      kRaftController:
        clusterRef:
          name: kraftcontroller
  kafkaRestProxy:
    name: kafkarestproxy
    replicas: 1
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-kafka-rest:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
    dependencies:
      schemaRegistry:
        url: http://schemaregistry.confluent.svc.cluster.local:8081
  kraftController:
    name: kraftcontroller
    dataVolumeCapacity: 10Gi
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-server:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
    replicas: 3
  ksqlDB:
    name: ksqldb
    replicas: 1
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-ksqldb-server:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
    dataVolumeCapacity: 10Gi
  schemaRegistry:
    name: schemaregistry
    replicas: 3
    image:
      application: "{{ .Values.confluent.imageRegistry }}/confluentinc/cp-schema-registry:7.7.0"
      init: "{{ .Values.confluent.imageRegistry }}/confluentinc/confluent-init-container:2.9.0"
