---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:andrekloster/confluent-test.git
    targetRevision: main
    path: kubernetes/apps/kafka-poc/confluent
    helm:
      releaseName: confluent
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
