---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-for-kubernetes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:andrekloster/confluent-test.git
    targetRevision: main
    path: kubernetes/apps/kafka-poc/confluent-for-kubernetes
    helm:
      releaseName: confluent-operator
    #  valueFiles:
    #    - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
