---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: {{ .Values.confluent.connect.name }}
  namespace: {{ .Values.confluent.namespace }}
spec:
  replicas: {{ .Values.confluent.connect.replicas }}
  image:
    application: {{ .Values.confluent.connect.image.application }}
    init: {{ .Values.confluent.connect.image.init }}
  dependencies:
    kafka:
      bootstrapEndpoint: {{ .Values.confluent.connect.dependencies.kafka.bootstrapEndpoint }}
