---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: {{ .Values.confluent.controlcenter.name }}
  namespace: {{ .Values.confluent.namespace }}
spec:
  replicas: {{ .Values.confluent.controlcenter.replicas }}
  image:
    application: {{ .Values.confluent.controlcenter.image.application }}
    init: {{ .Values.confluent.controlcenter.image.init }}
  dataVolumeCapacity: {{ .Values.confluent.controlcenter.dataVolumeCapacity }}
  listeners:
    external:
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: controlcenter.domus-server.local
  dependencies:
    schemaRegistry:
      url: {{ .Values.confluent.controlcenter.dependencies.schemaRegistry.url }}
    ksqldb:
    {{- range .Values.confluent.controlcenter.dependencies.ksqldb }}
      - name: {{ .name }}
        url: {{ .url }}
    {{- end }}
    connect:
    {{- range .Values.confluent.controlcenter.dependencies.connect }}
      - name: {{ .name }}
        url: {{ .url }}
    {{- end }}
