---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.confluent.kafka.name }}
  namespace: {{ .Values.confluent.namespace }}
spec:
  replicas: {{ .Values.confluent.kafka.replicas }}
  image:
    application: {{ .Values.confluent.kafka.image.application }}
    init: {{ .Values.confluent.kafka.image.init }}
  dataVolumeCapacity: {{ .Values.confluent.kafka.dataVolumeCapacity }}
  listeners:
    external:
      externalAccess:
        type: nodePort
        nodePort:
          host: {{ .Values.confluent.kafka.listeners.external.externalAccess.nodePort.host }}
          nodePortOffset: {{ .Values.confluent.kafka.listeners.external.externalAccess.nodePort.nodePortOffset }}
  dependencies:
    kRaftController:
      clusterRef:
        name: {{ .Values.confluent.kafka.dependencies.kRaftController.clusterRef.name }}
