---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: {{ .Values.confluent.schemaRegistry.name }}
  namespace: {{ .Values.confluent.namespace }}
spec:
  replicas: {{ .Values.confluent.schemaRegistry.replicas }}
  image:
    application: {{ .Values.confluent.schemaRegistry.image.application }}
    init: {{ .Values.confluent.schemaRegistry.image.init }}
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: schemaregistry.domus-server.local
      port: 8081
      externalTrafficPolicy: Cluster
      sessionAffinity: None
